# wt — multi-repo worktree manager.
# Loads the shell integration generated by the wt binary (`wt shell-init fish`).
# Managed by chezmoi; the integration below is generated by the wt binary.
if command -q wt
    wt shell-init fish | source
end
